title: Posts
description: Posts List
author: Sandesh Rana
github: https://github.com/vimm0
about: Hello (नमस्ते), I'm developer from Nepal.
#disqus_shortname: techproblems
#google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/github-pic.png
#
enableTags: true
tagarray: []
#
collections:
  project:
    output: true
    permalink: /project/:path/

social:
#    - icon: fa-facebook
#      link: "#"
    - icon: fa-twitter
      link: "https://twitter.com/vimm0"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/sandesh-rana-12783611a/"
#    - icon: fa-stack-exchange
#      link: "#"
    - icon: fa-github
      link: "https://github.com/vimm0"

share:
  twitter_username: vimm0
#  fb_appid: 1749788565247320
#
urls:
    - text: About Me
      url: /about/
#    - text: My Projects
#      url: /projects/
#    - text: XML Feed
#      url: /feed.xml
#
url: "https://vimm0.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
